server:
  port: 3998

eureka:
  instance:
    hostname: ${hostname}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:
        - ${protocol}://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInWhenSyncEmpty: 30000 # 30초에 한 번 씩 인스턴스 검색
